### ISSUE TITLE
Regarding the Raspberry Pi zero W OS , and it's set up.

### ISSUE THREAD

**Issue by dhan2001verma** [thewh1teagle/zero-hid#20]
Hi @thewh1teagle Good to see your contribution for this library.

I am using zero-hid for the emulating mouse actions.  For Hardware I am using Raspberry pi zero W.  I want to use RPI as USB device 
,not as a host to emulate the mouse action on the host computer. I am using Linux pc as a Host. I am using the OS - Bookworm 32 bit 
legacy.  I have configure all the set up ,that is there in readme file.  I am using  micro usb  for  for data and power.
configured ssh ,network ,everything in pi. 
Apart from these set up, Do i need to make any other changes in OS of Rpi.?
For OTG ,I have added   dtoverlay=dwc2 and modules-load=dwc2,g_ether in config.txt and cmdline.txt.
What OS you used for its testing, What set up you have done to work this library ? it is not working even after doing all the set up?
Please help.

**Comment by thewh1teagle** [comment]
Hello
Please follow the instructions in the readme. don't change manually. 
https://github.com/thewh1teagle/zero-hid?tab=readme-ov-file#setup

**Comment by dhan2001verma** [comment]
which Rpi OS is compatible with this zero-hid? Bro the py code is running in host terminal ,But mouse movement is not happening? I think issue is with OS?

**Comment by thewh1teagle** [comment]
> @thewh1teagle which Rpi OS is compatible with this zero-hid? Bro the py code is running in host terminal ,But mouse movement is not happening? I think issue is with OS? I am using linux PC as a host.

I tried that on latest rpi zero w 3 months ago.
All the info available in the readme

**Comment by dhan2001verma** [comment]
@thewh1teagle ok,which one you used Bullseye OS or Bookworm  OS.

**Comment by thewh1teagle** [comment]
https://github.com/thewh1teagle/zero-hid?tab=readme-ov-file#tests

Raspbian 12
I even documented the tests

**Comment by dhan2001verma** [comment]
BlI have no issue with that bro ,i have implemented your lib 
But when I am running the codes ,it is not working

**Comment by dhan2001verma** [comment]
https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-32-bit
See this now they have changed it , lite version is two.
One is Bullseye and another one Bookworm

**Comment by dhan2001verma** [comment]
@thewh1teagle 
Downloaded the image,configure ssh in host pc, downloaded the git,python3 in rpi zero, create virtual env that you also mentioned,enable the gadget.then make py file in venv and run ,also give the permission to dev/hidg1.
File was running but not making any movement.

**Comment by thewh1teagle** [comment]
I'm not sure why it doesn't work. My raspberry zero w died so I have only rpi 4 to try on it (and it worked there last month)
I suggest you to try again I'm pretty sure you missed something.
Download again raspbian lite, flash it with rpi imager.
Then follow the instruction in https://github.com/thewh1teagle/zero-hid?tab=readme-ov-file#setup I updated them today.

**Comment by thewh1teagle** [comment]
> Can we connect ,because i have set up ready now

https://linktr.ee/thewh1teagle

**Comment by dhan2001verma** [comment]
how to connect it

**Comment by dhan2001verma** [comment]
tested on fresh raspian still not working on pi zero

**Comment by thewh1teagle** [comment]
> tested on fresh raspian still not working on pi zero

Maybe you can try with another cable and another USB port

**Comment by dhan2001verma** [comment]
I am using charging cable

**Comment by thewh1teagle** [comment]
> I am using charging cable

https://t.me/thewh1teagle

Send me message in Telegram I'll try to help

**Comment by dhan2001verma** [comment]
Yeah i just send you hi

**Comment by thewh1teagle** [comment]
I’ve identified the issue: a breaking change in the latest Raspbian update was causing the gadget module to fail during installation. I’ve addressed this problem and released a new version. Please clone the repository again or pull the latest changes, and then set it up once again. Everything should work correctly now.
